### ISSUE TITLE
As a User (of any type), I want to be able to access to the "My Account page", so that I can edit my personal information

### ISSUE THREAD

**Issue by SachaKor** [SachaKor/SDP-PolyCrowd#73]
- [x] #92, #93 Add layouts for user's profile page, user's list of organised events
- [x] #92 Add an access profile button when the user is logged in from the main page 
- [x] #92 Allow user to navigate to list of friends from their profile page 
- [x] #94 Add the option when clicking on a friend's name, displays location on map 
- [x] #95 Fetch and filter events from Firebase
- [x] #113 
- [x] #110 
- [x] #136
